apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: flower-app-deployment 
  labels:
    first: app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels: 
        app: web 
    spec: 
      containers:
        - name: flower-cont 
          image: muralisocial123/sre-training-web:v1.1.0
          ports: 
            - containerPort: 3015
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: flower-app-svc 
spec: 
  selector: 
    app: web
  ports:
    - targetPort: 3015
      port: 3016 
      protocol: TCP 
  type: ClusterIP    
                  
    
    