apiVersion: v1 
kind: Pod 
metadata:
  name: multi-pod 
spec: 
  containers:
    - name: sample-cont 
      image: muralisocial123/clahan-app-web:v3.1.0
      ports: 
        - containerPort: 80 
    - name: flower-app 
      image:  muralisocial123/sre-training-web:v1.1.0
      ports:
        - containerPort: 3015
    
  